import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const browser = await chromium.connectOverCDP(process.env.OFFICE_CDP_URL || 'http://127.0.0.1:9225');
const page = browser.contexts().flatMap(context => context.pages()).find(candidate => candidate.url().startsWith('beings://desktop'));
assert(page, 'P4 requires packaged production renderer on 9225, not a Vite instance');
const prefix = 'p4-' + Date.now(), results = [];
const requests = [], failures = [], errors = [];
page.on('request', request => requests.push(request.url()));
page.on('requestfailed', request => failures.push(request.url()));
page.on('pageerror', error => errors.push(error.message));
const record = name => { results.push(name); console.log('PASS ' + name); };
const diagnostics = () => page.locator('.office-scene').evaluate(element => JSON.parse(element.dataset.officeDiagnostics));
let order = 0;
const report = async (beingId, fields) => {
  const receipt = await page.evaluate(input => window.beings.officeReport(input), { eventId: prefix + '-' + ++order, runId: prefix, beingId, ...fields });
  assert(receipt.accepted, JSON.stringify(receipt));
};
try {
  const viewportSession = await page.context().newCDPSession(page);
  await viewportSession.send("Emulation.setDeviceMetricsOverride", { width: 1600, height: 1100, deviceScaleFactor: 1, mobile: false });
  await page.evaluate(() => { localStorage.removeItem('beings:star-map:v4'); localStorage.setItem('starmap-office-open', 'true'); localStorage.setItem('starmap-office-reduced', 'true'); });
  await page.context().setOffline(true);
  await page.reload();
  await page.locator('#options-home button').filter({ hasText: '小镇' }).evaluate(button => button.click());
  await page.locator('.place-switcher button').filter({ hasText: '星图' }).click();
  await page.waitForFunction(() => { const node = document.querySelector('.office-scene'); return node?.dataset.officeDiagnostics && JSON.parse(node.dataset.officeDiagnostics).textures > 0; });
  const notices = await page.evaluate(async () => ({ notice: await (await fetch('beings://desktop/THIRD_PARTY_NOTICES')).text(), license: await (await fetch('beings://desktop/PIXOFFICE-LICENSE.txt')).text() }));
  assert(notices.notice.includes('Original PixOffice PNGs')); assert(notices.license.includes('Copyright (c) 2026 teejoo'));
  assert.equal(await page.locator('.office-scene canvas').count(), 1);
  assert.equal(await page.locator('.office-reduced').count(), 1);
  record('offline packaged office renders procedural textures and local license resources');
  assert(page.url().startsWith('beings://desktop'));
  const assets = await page.evaluate(() => [...new Set([...performance.getEntriesByType('resource').map(entry => entry.name), ...[...document.scripts].map(script => script.src), ...[...document.querySelectorAll('link[rel=stylesheet]')].map(link => link.href)])]);
  const loaded = await page.evaluate(async urls => Promise.all(urls.filter(url => /\.js|\.css/.test(url)).map(async url => { const response = await fetch(url); return { url, status: response.status, length: (await response.text()).length }; })), assets);
  assert(loaded.every(asset => asset.status === 200 && asset.length > 0), JSON.stringify(loaded));
  assert(assets.some(url => url.startsWith('beings://desktop/') && /\.js/.test(url)));
  assert(!assets.some(url => /^https?:.*:(5173|5174)\//.test(url)));
  assert(!requests.some(url => /^https?:.*:(5173|5174)\//.test(url)));
  const disabled = await page.evaluate(async () => { try { await window.beings.officeTestInject({}); return false; } catch { return true; } });
  assert(disabled, 'production must reject the dev injection API');
  record('production uses beings protocol without development-port dependencies; test injection remains disabled');
  const baseline = await diagnostics();
  for (let index = 0; index < 20; index++) {
    await page.locator('.office-heading button').first().click();
    await page.waitForFunction(() => JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics).ticker === false);
    const hidden = await diagnostics();
    assert.equal(hidden.applications, 1); assert.equal(hidden.maintenance, false);
    await page.locator('.office-heading button').first().click();
    await page.locator('.place-switcher button').filter({ hasText: '篝火' }).click();
    await page.waitForFunction(() => JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics).ticker === false);
    await page.locator('.place-switcher button').filter({ hasText: '星图' }).click();
    const current = await diagnostics();
    for (const key of ['applications', 'listeners', 'tickerListeners', 'sceneSubscriptions', 'resizeObservers']) assert.equal(current[key], baseline[key], key + ' leaked after cycle ' + index);
    assert.equal(current.maintenance, false);
    assert.equal(await page.locator('.office-scene canvas').count(), 1);
  }
  record('20 fold/open/view cycles retain one application with no ticker, observer or subscription growth');
  const snapshot = await page.evaluate(() => window.beings.officeSnapshot());
  const participants = snapshot.entries.filter(entry => entry.identity.demo).slice(0, 2).map(entry => entry.identity.id);
  await page.getByLabel('减少动态效果').uncheck();
  await report(participants[0], { type: 'presence', status: 'working', lastSeen: Date.now(), summary: '离线工作帧' });
  await page.waitForTimeout(700);
  await report(participants[0], { type: 'presence', status: 'thinking', lastSeen: Date.now(), summary: '离线思考帧' });
  await page.waitForTimeout(700);
  assert((await diagnostics()).textures > baseline.textures);
  await report(participants[0], { type: 'presence', status: 'idle', lastSeen: Date.now(), summary: '' });
  const handoffId = prefix + '-handoff', walkingBaseline = (await diagnostics()).textures;
  await report(participants[0], { type: 'handoff', handoffId, toBeingId: participants[1], mode: 'visual', summary: '生产离线工位交接', durationMs: 300 });
  await page.waitForFunction(() => document.querySelector('.office-activity-feedback').textContent.includes('completed'), undefined, { timeout: 90000 });
  await page.waitForFunction(() => { const value = JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics); return !value.transitions && !value.leisureMoving && !value.positionMismatches; }, undefined, { timeout: 60000 });
  assert((await diagnostics()).textures > walkingBaseline, 'handoff must generate walking textures');
  await page.getByLabel('减少动态效果').check();
  await page.screenshot({ path: 'test-results/office-p4-production.png' });
  assert.equal((await diagnostics()).positionMismatches, 0, 'rendered actors must follow runtime positions');
  record('offline production generates working/thinking/walking frames and completes workstation handoff/return');
  const runtimeId = (await diagnostics()).runtimeId;
  const ids = Array.from({ length: 10 }, (_, index) => prefix + '-person-' + index);
  for (const [index, id] of ids.entries()) await report(id, { type: 'register', identity: { id, name: 'P4 伙伴 ' + index, owners: [], assignedUsers: [], color: 0x426889, demo: false } });
  await page.waitForFunction(count => JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics).actors === count, baseline.actors + ids.length);
  assert.equal((await diagnostics()).runtimeId, runtimeId);
  assert.equal(await page.locator('.office-dock').getAttribute('data-detached'), 'true');
  assert.equal(await page.locator('.office-body').getAttribute('role'), 'dialog');
  await page.locator('.office-detached-close').click();
  assert.equal((await diagnostics()).ticker, false);
  await page.locator('.office-heading button').first().click();
  record('large roster opens independent office and new identities append without runtime replacement');
  for (const id of ids) await report(id, { type: 'unregister' });
  await page.waitForFunction(count => JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics).actors === count, baseline.actors);
  assert.equal(await page.locator('.office-scene canvas').count(), 1);
  assert.equal(errors.length, 0, errors.join('\n'));
  console.log('METRICS ' + JSON.stringify({ before: baseline, after: await diagnostics(), localAssets: assets.filter(url => url.startsWith('beings://desktop/')), networkFailures: failures }));
  console.log('SUMMARY ' + results.length + '/' + results.length + ' PASS');
} finally { await page.context().setOffline(false); await browser.close(); }
