import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const browser = await chromium.connectOverCDP(process.env.OFFICE_CDP_URL || 'http://127.0.0.1:9225');
const page = browser.contexts().flatMap(context => context.pages()).find(candidate => new RegExp('^http://(localhost|127[.]0[.]0[.]1):[0-9]+/').test(candidate.url()) || candidate.url().startsWith('beings://desktop'));
assert(page, 'P6 needs the isolated 9225 office');
const errors = [], requests = [], results = [], prefix = 'p6-' + Date.now();
page.on('pageerror', error => errors.push(error.message)); page.on('request', request => requests.push(request.url()));
const directory = process.env.OFFICE_SCREENSHOT_DIR || 'desktop/renderer/pipeline/office/p6-screenshots';
let viewportSession;
const capture = async (filename, clip) => { const image = await viewportSession.send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false, ...(clip ? { clip: { ...clip, scale: 1 } } : {}) }); await writeFile(directory + '/' + filename, Buffer.from(image.data, 'base64')); };
let order = 0;
const report = async (beingId, fields) => { const receipt = await page.evaluate(input => window.beings.officeReport(input), { beingId, runId: prefix, eventId: prefix + '-' + ++order, ...fields }); assert(receipt.accepted, JSON.stringify(receipt)); };
const diagnostics = () => page.locator('.office-scene').evaluate(element => JSON.parse(element.dataset.officeDiagnostics));
const settled = () => page.waitForFunction(() => { const value = JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics); return !value.transitions && !value.leisureMoving && !value.positionMismatches; }, undefined, { timeout: 30000 });
const record = text => { results.push(text); console.log('PASS ' + text); };
const seeds = [
  { id: 'demo-product', name: '产品伙伴', owners: ['产品 Agent'], assignedUsers: [], color: 0xe3a35d, demo: true },
  { id: 'demo-development', name: '开发伙伴', owners: ['开发 Agent'], assignedUsers: [], color: 0x6baec0, demo: true },
  { id: 'demo-test', name: '测试伙伴', owners: ['测试 Agent'], assignedUsers: [], color: 0x94b879, demo: true },
];
const roles = ['引擎开发', '后端开发', '前端开发', '产品', '测试', ''];
const identities = Array.from({ length: 10 }, (_, index) => ({ id: prefix + '-person-' + index, name: ['林 · 引擎', '陈 · 服务端', '周 · 界面', '许 · 产品', '何 · QA', '吴 · 协作'][index % 6], role: roles[index % 6], responsibilities: roles[index % 6] || '团队协作', owners: [], assignedUsers: [], color: [0x688e99, 0x829b7b, 0xbb956f, 0xc0a176, 0x8992ab, 0x739995][index % 6], demo: false }));
try {
  viewportSession = await page.context().newCDPSession(page);
  await viewportSession.send('Emulation.setDeviceMetricsOverride', { width: 2200, height: 1700, deviceScaleFactor: 2, mobile: false });
  await mkdir(directory, { recursive: true });
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.evaluate(() => { localStorage.removeItem('beings:star-map:v4'); localStorage.setItem('starmap-office-open', 'true'); localStorage.setItem('starmap-office-reduced', 'false'); });
  await page.reload();
  await page.locator('#options-home button').filter({ hasText: '小镇' }).evaluate(button => button.click());
  await page.locator('.place-switcher button').filter({ hasText: '星图' }).click();
  await page.getByRole('button', { name: '办公室 · 实验' }).click();
  await page.waitForFunction(() => document.querySelector('.office-scene')?.dataset.officeDiagnostics);
  for (const entry of (await page.evaluate(() => window.beings.officeSnapshot())).entries) await report(entry.identity.id, { type: 'unregister' });
  await page.waitForFunction(() => JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics).actors === 0);
  await settled();
  assert.equal((await diagnostics()).desks, 0);
  record('zero actual identities shows an empty studio, not decorative fixed agents');
  await report(identities[0].id, { type: 'register', identity: identities[0] });
  await report(identities[0].id, { type: 'presence', status: 'idle', lastSeen: Date.now(), summary: '' });
  await page.waitForFunction(() => JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics).transitions > 0);
  const firstStep = (await diagnostics()).visualActors[0];
  await page.waitForTimeout(220);
  const secondStep = (await diagnostics()).visualActors[0];
  assert(Math.hypot(firstStep.x - secondStep.x, firstStep.y - secondStep.y) > 5, 'entry must walk instead of fading in at the desk');
  const walkBounds = await page.locator('.office-scene').boundingBox(), walk = await diagnostics();
  const walkOrigin = { x: walkBounds.x + (walkBounds.width - walk.room.width * 50 * walk.scale) / 2, y: walkBounds.y + (walkBounds.height - walk.room.height * 50 * walk.scale) / 2 };
  await capture('06-walking-character.png', { x: Math.max(walkBounds.x, walkOrigin.x + (secondStep.x - 42) * walk.scale), y: Math.max(walkBounds.y, walkOrigin.y + (secondStep.y - 60) * walk.scale), width: 95 * walk.scale, height: 95 * walk.scale });
  await settled();
  const single = await diagnostics(); assert.equal(single.actors, 1); assert.equal(single.desks, 1);
  record('one actual identity walks from the door and occupies one adaptive workstation');
  for (const identity of identities.slice(1, 6)) { await report(identity.id, { type: 'register', identity }); await report(identity.id, { type: 'presence', status: 'idle', lastSeen: Date.now(), summary: '' }); }
  await page.waitForFunction(() => JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics).actors === 6);
  const registrations = (await diagnostics()).visualActors;
  assert(identities.slice(1, 6).every(identity => registrations.find(actor => actor.id === identity.id)?.state === 'walking'), 'rapid registrations preserve every new identity entry route');
  await settled();
  const six = await diagnostics(); assert.equal(six.desks, 6); assert(six.room.height > single.room.height);
  const tabs = await page.locator('.office-person-tabs').innerText();
  for (const role of ['引擎开发', '后端开发', '前端开发', '团队伙伴']) assert(tabs.includes(role), role);
  const bounds = await page.locator('.office-scene').boundingBox();
  await capture('01-office-panorama.png', bounds);
  const offset = { x: bounds.x + (bounds.width - six.room.width * 50 * six.scale) / 2, y: bounds.y + (bounds.height - six.room.height * 50 * six.scale) / 2 };
  const deskClip = { x: Math.round(offset.x + 66 * six.scale), y: Math.round(offset.y + 103 * six.scale), width: Math.round(185 * six.scale), height: Math.round(220 * six.scale) };
  await capture('02-workstation-detail.png', deskClip);
  await report(identities[0].id, { type: 'presence', status: 'thinking', lastSeen: Date.now(), summary: '检查渲染管线' });
  await page.waitForFunction(id => JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics).visualActors.find(actor => actor.id === id)?.seated, identities[0].id);
  await capture('03-character-detail.png', { x: Math.round(offset.x + 112 * six.scale), y: Math.round(offset.y + 151 * six.scale), width: Math.round(110 * six.scale), height: Math.round(115 * six.scale) });
  await capture('04-office-in-context.png');
  record('six roster-driven roles use distinct desks/screens; panorama and closeups captured');
  await report(identities[0].id, { type: 'presence', status: 'working', lastSeen: Date.now(), summary: '编译实时图形' });
  const activeBefore = (await diagnostics()).renders;
  await page.waitForTimeout(500); assert((await diagnostics()).renders > activeBefore);
  await report(identities[0].id, { type: 'presence', status: 'idle', lastSeen: Date.now(), summary: '' }); await settled();
  const hoveredActor = (await diagnostics()).visualActors.find(actor => actor.id === identities[0].id);
  await page.mouse.move(offset.x + hoveredActor.x * six.scale, offset.y + (hoveredActor.y - 15) * six.scale);
  await page.waitForFunction(id => JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics).hovered === id, identities[0].id);
  await page.waitForTimeout(350);
  assert.equal(await page.locator('[data-office-label="' + identities[0].id + '"]').getAttribute('data-emphasis'), 'true');
  assert((await diagnostics()).visualActors[0].scaleX > 1.03, 'hover enlargement survives character frame updates');
  await page.mouse.move(10, 10); await settled();
  await page.waitForFunction(() => JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics).visualActors[0].scaleX === 1);
  assert.equal((await diagnostics()).visualActors[0].scaleX, 1);
  record('working/thinking frames animate; hover highlights while scene activities animate');
  for (const identity of identities.slice(6)) { await report(identity.id, { type: 'register', identity }); await report(identity.id, { type: 'presence', status: 'idle', lastSeen: Date.now(), summary: '' }); }
  await page.waitForFunction(() => JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics).actors === 10); await settled();
  assert.equal((await diagnostics()).desks, 10);
  await capture('05-ten-people.png', await page.locator('.office-scene').boundingBox());
  await report(identities[9].id, { type: 'unregister' });
  await page.waitForFunction(() => JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics).transitions > 0);
  await settled();
  for (const identity of identities.slice(1, 9)) await report(identity.id, { type: 'unregister' });
  await page.waitForFunction(() => JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics).actors === 1);
  assert((await diagnostics()).transitions > 1, 'rapid unregisters preserve overlapping exits; already completed routes may leave');
  await settled();
  assert.deepEqual((await diagnostics()).room, single.room);
  record('ten identities remain data-driven; exit follows a route and room shrinks back to one');
  await report(identities[0].id, { type: 'presence', status: 'working', lastSeen: Date.now(), summary: '系统减弱动画验证' });
  await page.waitForFunction(id => document.querySelector('[data-office-actor="' + id + '"]')?.dataset.status === 'working', identities[0].id);
  await page.waitForTimeout(100);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.waitForFunction(() => JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics).reduced);
  await page.waitForTimeout(200);
  const reduced = await diagnostics(); await page.waitForTimeout(1800);
  assert.equal((await diagnostics()).renders, reduced.renders); assert.equal((await diagnostics()).ticker, false);
  assert.equal((await diagnostics()).breathing, false);
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await report(identities[0].id, { type: 'presence', status: 'idle', lastSeen: Date.now(), summary: '' });
  await settled();
  await page.getByRole('button', { name: '返回画布' }).click();
  await page.locator('.office-heading button').first().click();
  const hidden = await diagnostics(); await page.waitForTimeout(1800);
  assert.equal((await diagnostics()).renders, hidden.renders); assert.equal((await diagnostics()).ticker, false);
  record('live OS reduced-motion and collapsed office perform zero ongoing draws');
  assert.equal(errors.length, 0, errors.join(' | '));
  assert(!requests.some(url => /^https?:.*\.(png|jpg|woff2?)(?:[?#]|$)/i.test(url) && !new RegExp('^http://(localhost|127[.]0[.]0[.]1):').test(url)), 'no remote artwork/fonts');
  console.log('SUMMARY ' + results.length + '/' + results.length + ' PASS');
} finally {
  for (const entry of (await page.evaluate(() => window.beings.officeSnapshot())).entries.filter(entry => !entry.identity.demo)) await report(entry.identity.id, { type: 'unregister' });
  for (const identity of seeds) { await report(identity.id, { type: 'register', identity }); await report(identity.id, { type: 'presence', status: 'idle', lastSeen: Date.now(), summary: '演示绑定 · 来自流程状态' }); }
  await page.emulateMedia({ reducedMotion: 'no-preference' }); await browser.close();
}
