import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const browser = await chromium.connectOverCDP(process.env.OFFICE_CDP_URL || 'http://127.0.0.1:9225');
const page = browser.contexts().flatMap(context => context.pages()).find(page => page.url().match(/^http:\/\/(localhost|127\.0\.0\.1):\d+\//));
assert(page, 'P2 isolated renderer must use 9225 / isolated Vite');
const results = [], orders = new Map(), runs = new Map(), runBase = Date.now(), prefix = runBase + '-';
const record = name => { results.push(name); console.log('PASS ' + name); };
const send = async (beingId, fields) => {
  const eventOrder = (orders.get(beingId) || 0) + 1; orders.set(beingId, eventOrder);
  const runOrder = runs.get(beingId) || runBase;
  if (fields.handoffId) fields = { ...fields, handoffId: prefix + fields.handoffId };
  const input = { beingId, eventId: beingId + '-' + runOrder + '-' + eventOrder, runId: 'run-' + runOrder, runOrder, eventOrder, ...fields };
  const receipt = await page.evaluate(input => window.beings.officeTestInject(input), input);
  assert(receipt.accepted, JSON.stringify(receipt));
  return input;
};
const identity = id => ({ id, name: id + ' 真实伙伴', owners: [id], assignedUsers: [], color: id === 'alpha' ? 0xe3a35d : 0x6baec0, demo: false });
try {
  const initial = await page.evaluate(() => window.beings.officeSnapshot());
  for (const entry of initial.entries.filter(entry => !entry.identity.demo)) await send(entry.identity.id, { type: 'unregister' });
  await send('demo-product', { type: 'register', identity: { id: 'demo-product', name: '产品伙伴', owners: ['产品 Agent'], assignedUsers: [], color: 0xe3a35d, demo: true } });
  const viewportSession = await page.context().newCDPSession(page);
  await viewportSession.send("Emulation.setDeviceMetricsOverride", { width: 1600, height: 1100, deviceScaleFactor: 1, mobile: false });
  await page.evaluate(() => { localStorage.removeItem('beings:star-map:v4'); localStorage.setItem('starmap-office-open', 'true'); });
  await page.reload();
  await page.locator('#options-home button').filter({ hasText: '小镇' }).evaluate(button => button.click());
  await page.locator('.place-switcher button').filter({ hasText: '星图' }).click();
  await page.waitForFunction(() => document.querySelector('.office-scene canvas'));
  await page.evaluate(async () => {
    const { OfficeRuntime } = await import('/pipeline/office/vendor/runtime/OfficeRuntime.ts');
    window.__officeP2 = { runtime: null, ticks: 0, submits: 0 };
    const tick = OfficeRuntime.prototype.tick, submit = OfficeRuntime.prototype.submit;
    OfficeRuntime.prototype.tick = function(delta) { if (this.sceneId === 'starmap-office') { window.__officeP2.runtime = this; window.__officeP2.ticks++; } return tick.call(this, delta); };
    OfficeRuntime.prototype.submit = function(command) { if (this.sceneId === 'starmap-office') { window.__officeP2.submits++; window.__officeP2.runtime = this; } return submit.call(this, command); };
  });
  await send('alpha', { type: 'register', identity: identity('alpha') });
  await send('beta', { type: 'register', identity: identity('beta') });
  await page.waitForFunction(() => window.__officeP2.runtime?.readActors().some(actor => actor.id === 'beta'));
  const seenAt = Date.now();
  const presence = await send('alpha', { type: 'presence', status: 'working', lastSeen: seenAt, summary: '授权的工作摘要' });
  await send('beta', { type: 'presence', status: 'thinking', lastSeen: seenAt, summary: '授权的思考摘要' });
  await page.waitForFunction(() => window.__officeP2.runtime.readActors().find(actor => actor.id === 'alpha')?.presentation.status === 'working' && window.__officeP2.runtime.readActors().find(actor => actor.id === 'beta')?.presentation.status === 'thinking');
  assert.equal(await page.locator('[data-office-actor=alpha]').getAttribute('data-status'), 'working');
  assert.equal(await page.locator('[data-office-actor=beta]').getAttribute('data-status'), 'thinking');
  record('two real beings have independent working/thinking presence');
  const sequence = await page.evaluate(() => window.beings.officeSnapshot().then(snapshot => snapshot.sequence));
  const duplicate = await page.evaluate(input => window.beings.officeTestInject(input), presence);
  assert(duplicate.duplicate); assert.equal(duplicate.sequence, sequence);
  record('duplicate event returns same sequence and produces no new delta');
  runs.set('alpha', runBase + 1); orders.set('alpha', 0);
  await send('alpha', { type: 'presence', status: 'idle', lastSeen: Date.now() });
  const stale = await page.evaluate(input => window.beings.officeTestInject(input), { ...presence, eventId: 'late-old-run', eventOrder: 99 });
  assert.equal(stale.code, 'STALE_RUN');
  await page.waitForFunction(() => window.__officeP2.runtime.readActors().find(actor => actor.id === 'alpha')?.presentation.status === 'idle');
  record('old run cannot overwrite latest presence');
  await send('alpha', { type: 'handoff', toBeingId: 'beta', handoffId: 'unconfirmed', mode: 'business', summary: '等待接收方确认', durationMs: 300 });
  await page.waitForTimeout(150);
  assert.equal(await page.evaluate(() => window.__officeP2.runtime.snapshot().activities.length), 0);
  assert((await page.locator('.office-activity-feedback').innerText()).includes('awaiting_confirmation'));
  record('unconfirmed business handoff has no fake receipt or animation');
  const visual = await send('alpha', { type: 'handoff', toBeingId: 'beta', handoffId: 'visual', mode: 'visual', summary: '视觉拜访', durationMs: 300 });
  await page.waitForFunction(() => window.__officeP2.runtime.snapshot().activities.length === 1);
  assert.equal(await page.evaluate(() => window.__officeP2.runtime.snapshot().activities[0].plan.phases.flatMap(phase => phase.speech || []).some(speech => speech.text.includes('收到'))), false);
  await page.waitForFunction(() => window.__officeP2.runtime.readActors().find(actor => actor.id === 'alpha')?.step);
  await send('gamma', { type: 'register', identity: identity('gamma') });
  assert.equal(await page.evaluate(() => window.__officeP2.runtime.readActors().some(actor => actor.id === 'gamma')), false);
  await page.waitForFunction(() => window.__officeP2.runtime.readActors().some(actor => actor.id === 'gamma'));
  assert.equal(await page.locator('.office-scene canvas').count(), 1);
  record('dynamic binding waits for activity settlement and reuses one Pixi canvas');
  const business = await send('alpha', { type: 'handoff', toBeingId: 'beta', handoffId: 'confirmed', mode: 'business', summary: '真实业务交接', durationMs: 300 });
  await send('beta', { type: 'handoff-confirm', handoffId: 'confirmed' });
  await page.waitForFunction(() => window.__officeP2.runtime.snapshot().activities.some(activity => activity.capability === 'starmap.handoff'));
  assert(await page.evaluate(() => window.__officeP2.runtime.snapshot().activities.some(activity => activity.plan.phases.flatMap(phase => phase.speech || []).some(speech => speech.text === '收到 · 接收方已确认'))));
  await send('alpha', { type: 'cancel', targetEventId: business.eventId });
  await page.waitForFunction(() => window.__officeP2.runtime.snapshot().resources.every(resource => !resource.holders.length));
  record('receiver confirmation starts real handoff; cancellation settles and releases claims');
  await send('alpha', { type: 'disconnect' });
  await page.waitForFunction(() => document.querySelector('[data-office-actor=alpha]')?.getAttribute('data-stale') === 'true');
  assert((await page.locator('[data-office-actor=alpha]').innerText()).includes('最后更新'));
  await page.reload();
  await page.locator('#options-home button').filter({ hasText: '小镇' }).evaluate(button => button.click());
  await page.locator('.place-switcher button').filter({ hasText: '星图' }).click();
  await page.waitForFunction(() => document.querySelector('[data-office-actor=alpha]')?.getAttribute('data-stale') === 'true');
  await page.evaluate(async () => {
    const { OfficeRuntime } = await import('/pipeline/office/vendor/runtime/OfficeRuntime.ts');
    window.__officeP2 = { runtime: null, ticks: 0 }; const tick = OfficeRuntime.prototype.tick;
    OfficeRuntime.prototype.tick = function(delta) { window.__officeP2.runtime = this; window.__officeP2.ticks++; return tick.call(this, delta); };
  });
  await page.waitForFunction(() => window.__officeP2.runtime);
  assert.equal(await page.evaluate(() => window.__officeP2.runtime.snapshot().activities.length), 0);
  await send('alpha', { type: 'presence', status: 'working', lastSeen: Date.now() });
  await page.waitForFunction(() => document.querySelector('[data-office-actor=alpha]')?.getAttribute('data-stale') === 'false');
  record('disconnect retains last seen/gray snapshot; reconnect restores snapshot without activity replay');
  await send('demo-product', { type: 'unregister' });
  await send('alpha', { type: 'register', identity: { ...identity('alpha'), owners: ['产品 Agent'] } });
  await page.waitForFunction(() => !document.querySelector('[data-office-actor=demo-product]'));
  const demandId = await page.evaluate(() => JSON.parse(localStorage.getItem('beings:star-map:v4')).demands[0].id);
  await send('alpha', { type: 'node', demandId, nodeId: 'N01', status: 'blocked', reason: '接口依赖尚未交付' });
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('beings:star-map:v4')).demands[0].nodeStates.N01 === 'blocked');
  await page.locator('[data-office-actor=alpha]').click();
  assert((await page.locator('[data-office-task="' + demandId + ':N01"]').first().innerText()).includes('接口依赖尚未交付'));
  assert((await page.locator('[data-office-task="' + demandId + ':N01"]').first().innerText()).includes('由 alpha 上报'));
  await send('alpha', { type: 'node', demandId, nodeId: 'N01', status: 'waiting_human', reason: '请确认授权范围' });
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('beings:star-map:v4')).demands[0].nodeOverrides.N01.stateReason === '请确认授权范围');
  record('formal blocked/review reasons and being source persist through real IPC');
  await send('alpha', { type: 'node', demandId, nodeId: 'H1', status: 'done', reason: '不应绕过人工审批' });
  await page.waitForTimeout(150);
  assert.notEqual(await page.evaluate(() => JSON.parse(localStorage.getItem('beings:star-map:v4')).demands[0].nodeStates.H1), 'done');
  assert(/NOT_ASSIGNED|HUMAN_REVIEW_REQUIRED/.test(await page.locator('.office-activity-feedback').innerText()));
  record('unassigned/gate report never approves human gate');
  await page.getByRole('button', { name: '▾ 协作舱', exact: true }).click();
  const ticks = await page.evaluate(() => window.__officeP2.ticks);
  const hidden = await send('alpha', { type: 'handoff', toBeingId: 'beta', handoffId: 'hidden', mode: 'visual', summary: '隐藏不补播', durationMs: 300 });
  await page.waitForTimeout(350);
  assert.equal(await page.evaluate(() => window.__officeP2.ticks), ticks);
  await page.getByRole('button', { name: '▸ 协作舱', exact: true }).click();
  await page.waitForTimeout(150);
  assert.equal(await page.evaluate(() => window.__officeP2.runtime.snapshot().activities.length), 0);
  record('hidden office has zero ticks and does not replay hidden handoffs');
  await send('gamma', { type: 'unregister' });
  await page.waitForFunction(() => !document.querySelector('[data-office-actor=gamma]'));
  assert.equal(await page.locator('.office-scene canvas').count(), 1);
  record('runtime unregister removes actor/binding without duplicating Pixi instance');
  console.log('SUMMARY ' + results.length + '/' + results.length + ' PASS');
} finally { await browser.close(); }
