import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const browser = await chromium.connectOverCDP(process.env.OFFICE_CDP_URL || 'http://127.0.0.1:9225');
const page = browser.contexts().flatMap(context => context.pages()).find(candidate => candidate.url().match(/^http:\/\/(localhost|127\.0\.0\.1):\d+\//));
assert(page, '9225 must contain the isolated Vite renderer');
const results = [];
const record = (name, detail = '') => { results.push(name); console.log('PASS ' + name + (detail ? ' | ' + detail : '')); };
const readState = () => page.evaluate(() => JSON.parse(localStorage.getItem('beings:star-map:v4')));
const openPipeline = async () => {
  await page.locator('#options-home button').filter({ hasText: '小镇' }).evaluate(button => button.click());
  await page.locator('.place-switcher button').filter({ hasText: '星图' }).click();
};
const viewport = async (width, height) => { const session = await page.context().newCDPSession(page); await session.send("Emulation.setDeviceMetricsOverride", { width, height, deviceScaleFactor: 1, mobile: false }); };
const openOffice = async () => {
  if (await page.locator(".office-heading > button").first().getAttribute("aria-expanded") === "false") await page.locator(".office-heading > button").first().click();
  const standalone = page.getByRole("button", { name: "打开独立协作舱" });
  if (await standalone.isVisible()) await standalone.click();
};
const navigate = async nodeId => {
  await openOffice();
  const state = await readState();
  const demand = state.demands.find(item => item.workflowId === 'beings-development') || state.demands[0];
  const selector = '[data-office-task="' + demand.id + ':' + nodeId + '"]';
  const button = page.locator(selector).first();
  if (!(await button.isVisible())) await page.locator('.office-person-tabs button').first().click();
  await page.locator(selector).first().click();
  await page.getByRole('button', { name: '在画布中打开', exact: true }).click();
};
const setStatus = async (nodeId, status) => {
  await navigate(nodeId);
  if (nodeId === 'H1' && status === 'done') {
    await page.locator('.pipeline-more-info summary').click();
    await page.getByLabel('拍板人', { exact: true }).fill('P1 隔离测试审核人');
    await page.locator('.pipeline-detail-description textarea').fill('P1 隔离测试审核完成，具备测试证据。');
  }
  await page.locator('.pipeline-detail-meta select').selectOption(status);
};
try {
  await viewport(1600, 1100);
  await page.evaluate(() => { localStorage.removeItem('beings:star-map:v4'); localStorage.setItem('starmap-office-open', 'true'); });
  await page.reload(); await openPipeline();
  await page.waitForFunction(() => document.querySelector('.office-scene canvas'));
  await page.evaluate(async () => {
    const { OfficeRuntime } = await import('/pipeline/office/vendor/runtime/OfficeRuntime.ts');
    window.__officeTest = { submits: 0, ticks: 0, runtime: null, lastAt: 0 };
    const submit = OfficeRuntime.prototype.submit, tick = OfficeRuntime.prototype.tick;
    OfficeRuntime.prototype.submit = function(command) { if (this.sceneId === 'starmap-office') { window.__officeTest.submits++; window.__officeTest.runtime = this; window.__officeTest.lastAt = performance.now(); } return submit.call(this, command); };
    OfficeRuntime.prototype.tick = function(delta) { if (this.sceneId === 'starmap-office') { window.__officeTest.ticks++; window.__officeTest.runtime = this; } return tick.call(this, delta); };
  });
  await page.waitForTimeout(200);
  assert.equal(await page.locator('.office-scene canvas').count(), 1);
  assert((await page.locator('.star-map-canvas').boundingBox()).height >= 360);
  record('single Pixi canvas; flow canvas remains >=360px');
  await setStatus('H1', 'done'); await setStatus('N01', 'ready');
  assert.equal((await readState()).demands[0].nodeStates.N02, 'ready');
  record('original gate approval unlocks downstream N02');
  await page.waitForTimeout(150);
  assert.equal(await page.locator('[data-office-actor="demo-product"]').getAttribute('data-status'), 'idle');
  const started = await page.evaluate(() => performance.now());
  await page.locator('.pipeline-detail-meta select').selectOption('running');
  await page.waitForFunction(() => window.__officeTest.runtime.readActors()[0].presentation.status === 'working', null, { timeout: 250 });
  const latency = await page.evaluate(start => window.__officeTest.lastAt - start, started);
  assert(latency <= 250, 'projection latency ' + latency);
  record('ready idle / running working / projection <=250ms', Math.round(latency) + 'ms including UI action');
  await page.locator('.pipeline-detail-meta select').selectOption('blocked');
  await page.waitForFunction(() => window.__officeTest.runtime.readActors()[0].presentation.status === 'idle');
  assert((await page.locator('[data-office-actor="demo-product"]').textContent()).includes('阻塞'));
  record('blocked never becomes thinking');
  assert.equal(await page.locator('[data-office-actor="demo-product"]').getAttribute('data-highlighted'), 'true');
  record('node selection highlights executor workstation');
  await openOffice();
  const actorPoint = await page.evaluate(async () => {
    const { CELL_PIXELS } = await import('/pipeline/office/vendor/scene/gridProjection.ts');
    const runtime = window.__officeTest.runtime, world = runtime.readWorld();
    const actor = JSON.parse(document.querySelector('.office-scene').dataset.officeDiagnostics).visualActors.find(actor => actor.id === 'demo-test');
    const bounds = document.querySelector('.office-scene canvas').getBoundingClientRect();
    const scale = Math.min(bounds.width / (world.width * CELL_PIXELS), bounds.height / (world.height * CELL_PIXELS));
    return { x: bounds.x + (bounds.width - world.width * CELL_PIXELS * scale) / 2 + actor.x * scale, y: bounds.y + (bounds.height - world.height * CELL_PIXELS * scale) / 2 + (actor.y - 15) * scale };
  });
  await page.mouse.click(actorPoint.x, actorPoint.y);
  assert.equal(await page.locator('[data-office-actor="demo-test"]').getAttribute('aria-pressed'), 'true');
  record('pixel character click opens that identity and task list');
  await page.locator('.office-person-tabs button').nth(1).click();
  await page.locator('.office-task-list > button').first().click();
  await page.getByRole('button', { name: '在画布中打开', exact: true }).click();
  assert(await page.locator('.react-flow__node.selected').count());
  record('person task navigates to track and selects node');
  await openOffice();
  await page.locator('.office-person-tabs button').first().click();
  await setStatus('H1', 'waiting_human');
  await page.locator('.office-review').click();
  await page.getByRole('button', { name: '在画布中打开', exact: true }).click();
  assert((await page.locator('.react-flow__node.selected').getAttribute('data-id')) === 'H1');
  record('human review shortcut selects gate without approving it');
  await openOffice();
  await page.locator('[data-office-actor="demo-product"]').click();
  await page.waitForTimeout(150);
  assert(await page.evaluate(() => Boolean(document.activeElement.closest('.office-dock'))), 'office controls must own keyboard focus');
  const stateBeforeKeys = JSON.stringify(await readState());
  await page.keyboard.press('Delete'); await page.keyboard.press('Control+z');
  assert.equal(JSON.stringify(await readState()), stateBeforeKeys);
  record('Delete and Ctrl+Z do not reach flow shortcuts');
  if (await page.locator(".office-detached-close").isVisible()) await page.locator(".office-detached-close").click();
  const submissions = await page.evaluate(() => window.__officeTest.submits);
  const pane = await page.locator('.star-map-canvas').boundingBox();
  await page.mouse.move(pane.x + pane.width / 2, pane.y + 60);
  await page.mouse.wheel(0, -120);
  await page.mouse.down({ button: 'middle' }); await page.mouse.move(pane.x + pane.width / 2 + 25, pane.y + 65); await page.mouse.up({ button: 'middle' });
  await page.waitForTimeout(180);
  assert.equal(await page.evaluate(() => window.__officeTest.submits), submissions);
  record('canvas pan and zoom submit no actor commands');
  await page.locator('.office-heading > button').first().click();
  await page.waitForTimeout(80);
  const ticks = await page.evaluate(() => window.__officeTest.ticks);
  await page.waitForTimeout(250);
  assert.equal(await page.evaluate(() => window.__officeTest.ticks), ticks);
  record('collapsed office has no simulation/render ticker');
  await page.locator('.office-heading > button').first().click();
  await page.locator('.pipeline-focus-button').click();
  assert.equal(await page.locator('.office-dock').getAttribute('data-expanded'), 'false');
  await page.locator('.pipeline-focus-button').click();
  assert.equal(await page.locator('.office-dock').getAttribute('data-expanded'), 'true');
  record('focus mode collapses dock and restores preference');
  await viewport(1266, 823);
  await page.getByRole('button', { name: '打开独立协作舱' }).click();
  assert(await page.getByRole('dialog', { name: '独立协作舱' }).isVisible());
  assert.equal(await page.locator('.office-scene canvas').count(), 1);
  await page.keyboard.press('Escape');
  assert(!(await page.getByRole('dialog', { name: '独立协作舱' }).isVisible()));
  record('small-window standalone office reuses same canvas');
  await page.setViewportSize({ width: 1600, height: 1100 });
  for (let index = 0; index < 20; index++) {
    await page.locator('.office-heading > button').first().click();
    await page.locator('.office-heading > button').first().click();
  }
  assert.equal(await page.locator('.office-scene canvas').count(), 1);
  record('20 collapse/open cycles retain one canvas');
  const markerBeforeReload = await page.locator('[data-office-actor="demo-product"]').textContent();
  await page.reload(); await openPipeline();
  assert.equal(await page.locator('[data-office-actor="demo-product"]').textContent(), markerBeforeReload);
  assert.equal((await readState()).demands[0].nodeStates.H1, 'waiting_human');
  record('reload restores projection without replaying historical activity');
  console.log('SUMMARY ' + results.length + '/' + results.length + ' PASS');
} finally { await browser.close(); }
